### PR TITLE
update virtual disk request for vm reconfiguration

### PR DESCRIPTION
**Pull request by ariquinones**

### CODE REVIEW

**Comment by cfsnyder** [comment]
VirtualDiskJson only coincidentally has the same representation as the disk config request object for the vm reconfiguration endpoint. i.e. they are different models server-side. You should generate a new/separate TS interface for that model using the IDEA plugin.

**Comment by cfsnyder** [comment]
@ariquinones  please rebase on master to fix the tests

**Comment by ariquinones** [comment]
@cfsnyder there it is, I had to force-push it should be good now

**Comment by cfsnyder** [comment]
thanks @ariquinones !

**Pull request merged**
