### PR TITLE
Update the getVacCompanies() to get all tenants without locationID

### PR DESCRIPTION
**Pull request by JoMas971**

### CODE REVIEW

**Comment by JoMas971** [comment]
This PR need to be merged before http://issues.iland.test/browse/IP-3856. This is a bugfix for prod.

**Comment by cfsnyder** [comment]
@JoMas971  - do you expect that integration test to be failing?

**Comment by JoMas971** [comment]
> @JoMas971 - do you expect that integration test to be failing?

Hum, nope... Let me check why it fail.

**Comment by JoMas971** [comment]
@cfsnyder integration tests has been fixed for BaCompany. It should be good now.

**Pull request merged**
